---
- name: Wait for SSH
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        timeout: 60

- name: Configure dev machine
  hosts: all
  become: true
  vars_files:
    - vars.yml
  roles:
    - common
    - deno
